# Generated by Django 4.2.4 on 2023-08-20 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shop_main.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Product', max_length=100),
        ),
    ]
